#ifndef BUILTINS_H 
#define BUILTINS_H
#include "includes.h"
#include "astnodes.h"
#include "banter_type.h"
BanterType *intType;
BanterType *boolType;
BanterType *FileType;
BanterType *voidType;
BanterType *methodType;
BanterType *letType;
BanterType *RangeType;
BanterType *ProgramType;
BanterType *stringType;
BanterType *typeType;
BanterType *cType;
BanterType *typeBuilderType;
BanterType *typeExtendType;
BanterType *BlockType;
BanterType *initialiserType;
BanterType *methodDefineType;
void initBuiltins(void);
#endif
