#ifndef INCLUDE_HEADER_FILE
#define INCLUDE_HEADER_FILE
#include <errno.h>
#include <fcntl.h>
#include <locale.h>
#include <math.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <ctype.h>
#include <unistd.h>
#include <wchar.h>
#include <sys/wait.h>
//#include <pthread.h>
//#include <signal.h>
//#include <netdb.h>
#endif
